-- Database Schema for Media Logging Application
-- Run these SQL statements in your Supabase SQL Editor

-- Create a table for public profiles
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  enabled_media_types text not null default 'games,movies,shows,books',
  last_synced timestamp,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security for more details.
alter table profiles
  enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check ((select auth.uid()) = id);

create policy "Users can update own profile." on profiles
  for update using ((select auth.uid()) = id);

-- This trigger automatically creates a profile entry when a new user signs up via Supabase Auth.
-- See https://supabase.com/docs/guides/auth/managing-user-data#using-triggers for more details.
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, updated_at)
  values (new.id, new.raw_user_meta_data->>'username', now());
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Create following schema
create table following (
  id bigint primary key generated always as identity,
  follower uuid not null references auth.users on delete cascade,
  followee uuid not null references auth.users on delete cascade
);

-- Create preference_profiles
create table
  preference_profiles (
    id bigint primary key generated always as identity,
    user_id uuid not null references auth.users on delete cascade,
    name varchar(50) not null,
    unique (user_id, name)
  );

-- IGDB stored
create table igdb_store (
  id bigint primary key generated always as identity,
  token text not null,
  created timestamptz not null,
  expires_in int not null
);

-- Create preferences
create table
  preferences (
    id bigint primary key generated always as identity,
    user_preference_id bigint not null references preference_profiles on delete cascade,
    tmdb_id bigint not null,
    name varchar(50) not null,
    factor real not null,
    unique (user_preference_id, tmdb_id)
  );

-- Create games
create table
  games (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users on delete cascade,
    igdbid int,
    title text,
    image text,
    release timestamp,
    genres text,
    platforms text,
    averagerating real,
    trophy int,
    added timestamp,
    rating real default 2.5,
    backlogged int default 0,
    is_rewatch boolean default false,
    rewatch_count int default 0,
    notes text
  );

-- Create movies
create table
  movies (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users on delete cascade,
    tmdbid int,
    title text,
    image text,
    release timestamp,
    genres text,
    averagerating real,
    added timestamp,
    rating real default 2.5,
    backlogged int default 0,
    is_rewatch boolean default false,
    rewatch_count int default 0,
    notes text
  );

-- Create shows
create table
  shows (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users on delete cascade,
    tmdbid int,
    title text,
    image text,
    release timestamp,
    genres text,
    seasons text,
    episode int default 0,
    averagerating real,
    added timestamp,
    rating real default 2.5,
    backlogged int default 0,
    is_rewatch boolean default false,
    rewatch_count int default 0,
    notes text
  );

-- Create books
create table
  books (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users on delete cascade,
    gbid text,
    title text,
    subtitle text,
    image text,
    author text,
    pagecount int,
    release timestamp,
    averagerating real,
    added timestamp,
    rating real default 2.5,
    backlogged int default 0,
    is_rewatch boolean default false,
    rewatch_count int default 0,
    notes text,
    genres text
  );

-- Create user challenges (year + medium specific goals)
create table
  user_challenges (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users on delete cascade,
    medium text not null,
    year int not null,
    challenge_type text not null check (challenge_type in ('count', 'pages', 'completion')),
    label text not null,
    target_count int not null check (target_count > 0),
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now(),
    unique (user_id, medium, year, challenge_type)
  );

alter table user_challenges enable row level security;

create policy "Users can view all challenges." on user_challenges
  for select using (true);

create policy "Users can insert own challenges." on user_challenges
  for insert with check ((select auth.uid()) = user_id);

create policy "Users can update own challenges." on user_challenges
  for update using ((select auth.uid()) = user_id);

create policy "Users can delete own challenges." on user_challenges
  for delete using ((select auth.uid()) = user_id);

-- Stored procedure for upserting preferences
CREATE OR REPLACE FUNCTION upsert_and_change_factor(r_user_preference_id bigint, r_tmdb_id bigint, r_name varchar(50), r_factor real) RETURNS VOID AS $$
BEGIN
    INSERT INTO preferences (user_preference_id, tmdb_id, name, factor)
    VALUES (r_user_preference_id, r_tmdb_id, r_name, r_factor)
    ON CONFLICT (user_preference_id, tmdb_id)
    DO UPDATE SET factor = preferences.factor + r_factor;
END;
$$ LANGUAGE plpgsql;
