-- Database Schema for Media Logging Application
-- Run these SQL statements in your Supabase SQL Editor

-- Create a table for public profiles
create table if not exists profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  enabled_media_types text not null default 'games,movies,shows,books,music',
  last_synced timestamp,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security for more details.
alter table profiles
  enable row level security;

drop policy if exists "Public profiles are viewable by everyone." on profiles;
create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

drop policy if exists "Users can insert their own profile." on profiles;
create policy "Users can insert their own profile." on profiles
  for insert with check ((select auth.uid()) = id);

drop policy if exists "Users can update own profile." on profiles;
create policy "Users can update own profile." on profiles
  for update using ((select auth.uid()) = id);

-- This trigger automatically creates a profile entry when a new user signs up via Supabase Auth.
-- See https://supabase.com/docs/guides/auth/managing-user-data#using-triggers for more details.
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, updated_at)
  values (new.id, new.raw_user_meta_data->>'username', now());
  return new;
end;
$$ language plpgsql security definer;

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'on_auth_user_created'
      and tgrelid = 'auth.users'::regclass
      and not tgisinternal
  ) then
    create trigger on_auth_user_created
      after insert on auth.users
      for each row execute procedure public.handle_new_user();
  end if;
end;
$$;

-- Create following schema
create table if not exists following (
  id bigint primary key generated always as identity,
  follower uuid not null references auth.users on delete cascade,
  followee uuid not null references auth.users on delete cascade
);

-- Create preference_profiles
create table if not exists
  preference_profiles (
    id bigint primary key generated always as identity,
    user_id uuid not null references auth.users on delete cascade,
    name varchar(50) not null,
    unique (user_id, name)
  );

-- IGDB stored
create table if not exists igdb_store (
  id bigint primary key generated always as identity,
  token text not null,
  created timestamptz not null,
  expires_in int not null
);

-- Create preferences
create table if not exists
  preferences (
    id bigint primary key generated always as identity,
    user_preference_id bigint not null references preference_profiles on delete cascade,
    tmdb_id bigint not null,
    name varchar(50) not null,
    factor real not null,
    unique (user_preference_id, tmdb_id)
  );

-- Create games
create table if not exists
  games (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users on delete cascade,
    igdbid int,
    title text,
    image text,
    release timestamp,
    genres text,
    platforms text,
    averagerating real,
    trophy int,
    added timestamp,
    rating real default 2.5,
    backlogged int default 0,
    is_rewatch boolean default false,
    rewatch_count int default 0,
    notes text
  );

-- Create movies
create table if not exists
  movies (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users on delete cascade,
    tmdbid int,
    title text,
    image text,
    release timestamp,
    genres text,
    averagerating real,
    added timestamp,
    rating real default 2.5,
    backlogged int default 0,
    is_rewatch boolean default false,
    rewatch_count int default 0,
    notes text
  );

-- Create shows
create table if not exists
  shows (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users on delete cascade,
    tmdbid int,
    title text,
    image text,
    release timestamp,
    genres text,
    seasons text,
    episode int default 0,
    averagerating real,
    added timestamp,
    rating real default 2.5,
    backlogged int default 0,
    is_rewatch boolean default false,
    rewatch_count int default 0,
    notes text
  );

-- Create books
create table if not exists
  books (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users on delete cascade,
    gbid text,
    title text,
    subtitle text,
    image text,
    author text,
    pagecount int,
    release timestamp,
    averagerating real,
    added timestamp,
    rating real default 2.5,
    backlogged int default 0,
    is_rewatch boolean default false,
    rewatch_count int default 0,
    notes text,
    genres text
  );

-- Create music releases (albums, EPs, and singles)
create table if not exists
  music (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users on delete cascade,
    mbid text,
    title text,
    artist text,
    music_type text not null default 'album' check (music_type in ('album', 'ep', 'single')),
    image text,
    release timestamp,
    genres text,
    averagerating real,
    added timestamp,
    rating real default 2.5,
    backlogged int default 0,
    is_rewatch boolean default false,
    rewatch_count int default 0,
    notes text
  );

alter table music enable row level security;

drop policy if exists "Music entries are viewable by everyone." on music;
create policy "Music entries are viewable by everyone."
  on music
  for select using (true);

drop policy if exists "Users can insert their own music entries." on music;
create policy "Users can insert their own music entries."
  on music
  for insert with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own music entries." on music;
create policy "Users can update their own music entries."
  on music
  for update
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their own music entries." on music;
create policy "Users can delete their own music entries."
  on music
  for delete using ((select auth.uid()) = user_id);

-- Media tables are public-readable for profile pages, while writes remain
-- restricted to the owning user. These policies are also applied to an
-- existing database where RLS may already be enabled without policies.
alter table games enable row level security;

drop policy if exists "Games entries are viewable by everyone." on games;
create policy "Games entries are viewable by everyone."
  on games
  for select using (true);

drop policy if exists "Users can insert their own games entries." on games;
create policy "Users can insert their own games entries."
  on games
  for insert with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own games entries." on games;
create policy "Users can update their own games entries."
  on games
  for update
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their own games entries." on games;
create policy "Users can delete their own games entries."
  on games
  for delete using ((select auth.uid()) = user_id);

alter table movies enable row level security;

drop policy if exists "Movies entries are viewable by everyone." on movies;
create policy "Movies entries are viewable by everyone."
  on movies
  for select using (true);

drop policy if exists "Users can insert their own movies entries." on movies;
create policy "Users can insert their own movies entries."
  on movies
  for insert with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own movies entries." on movies;
create policy "Users can update their own movies entries."
  on movies
  for update
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their own movies entries." on movies;
create policy "Users can delete their own movies entries."
  on movies
  for delete using ((select auth.uid()) = user_id);

alter table shows enable row level security;

drop policy if exists "Shows entries are viewable by everyone." on shows;
create policy "Shows entries are viewable by everyone."
  on shows
  for select using (true);

drop policy if exists "Users can insert their own shows entries." on shows;
create policy "Users can insert their own shows entries."
  on shows
  for insert with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own shows entries." on shows;
create policy "Users can update their own shows entries."
  on shows
  for update
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their own shows entries." on shows;
create policy "Users can delete their own shows entries."
  on shows
  for delete using ((select auth.uid()) = user_id);

alter table books enable row level security;

drop policy if exists "Books entries are viewable by everyone." on books;
create policy "Books entries are viewable by everyone."
  on books
  for select using (true);

drop policy if exists "Users can insert their own books entries." on books;
create policy "Users can insert their own books entries."
  on books
  for insert with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own books entries." on books;
create policy "Users can update their own books entries."
  on books
  for update
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their own books entries." on books;
create policy "Users can delete their own books entries."
  on books
  for delete using ((select auth.uid()) = user_id);

-- Following relationships are visible only to users involved in them.
alter table following enable row level security;

drop policy if exists "Users can view their own following relationships." on following;
create policy "Users can view their own following relationships."
  on following
  for select using ((select auth.uid()) = follower or (select auth.uid()) = followee);

drop policy if exists "Users can follow other users." on following;
create policy "Users can follow other users."
  on following
  for insert with check ((select auth.uid()) = follower);

drop policy if exists "Users can update their own following relationships." on following;
create policy "Users can update their own following relationships."
  on following
  for update
  using ((select auth.uid()) = follower)
  with check ((select auth.uid()) = follower);

drop policy if exists "Users can unfollow users." on following;
create policy "Users can unfollow users."
  on following
  for delete using ((select auth.uid()) = follower);

-- Preference tables are scoped through their owning preference profile.
alter table preference_profiles enable row level security;

drop policy if exists "Users can view their own preference profiles." on preference_profiles;
create policy "Users can view their own preference profiles."
  on preference_profiles
  for select using ((select auth.uid()) = user_id);

drop policy if exists "Users can create their own preference profiles." on preference_profiles;
create policy "Users can create their own preference profiles."
  on preference_profiles
  for insert with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own preference profiles." on preference_profiles;
create policy "Users can update their own preference profiles."
  on preference_profiles
  for update
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their own preference profiles." on preference_profiles;
create policy "Users can delete their own preference profiles."
  on preference_profiles
  for delete using ((select auth.uid()) = user_id);

alter table preferences enable row level security;

drop policy if exists "Users can view their own preferences." on preferences;
create policy "Users can view their own preferences."
  on preferences
  for select using (
    exists (
      select 1
      from preference_profiles
      where preference_profiles.id = preferences.user_preference_id
        and preference_profiles.user_id = (select auth.uid())
    )
  );

drop policy if exists "Users can create their own preferences." on preferences;
create policy "Users can create their own preferences."
  on preferences
  for insert with check (
    exists (
      select 1
      from preference_profiles
      where preference_profiles.id = preferences.user_preference_id
        and preference_profiles.user_id = (select auth.uid())
    )
  );

drop policy if exists "Users can update their own preferences." on preferences;
create policy "Users can update their own preferences."
  on preferences
  for update
  using (
    exists (
      select 1
      from preference_profiles
      where preference_profiles.id = preferences.user_preference_id
        and preference_profiles.user_id = (select auth.uid())
    )
  )
  with check (
    exists (
      select 1
      from preference_profiles
      where preference_profiles.id = preferences.user_preference_id
        and preference_profiles.user_id = (select auth.uid())
    )
  );

drop policy if exists "Users can delete their own preferences." on preferences;
create policy "Users can delete their own preferences." on preferences
  for delete using (
    exists (
      select 1
      from preference_profiles
      where preference_profiles.id = preferences.user_preference_id
        and preference_profiles.user_id = (select auth.uid())
    )
  );

-- The IGDB token is shared by authenticated server requests. Edge functions
-- using the service role bypass RLS as usual.
alter table igdb_store enable row level security;

drop policy if exists "Authenticated users can use the IGDB token store." on igdb_store;
create policy "Authenticated users can use the IGDB token store."
  on igdb_store
  for all
  using ((select auth.role()) = 'authenticated')
  with check ((select auth.role()) = 'authenticated');

alter table profiles
  alter column enabled_media_types set default 'games,movies,shows,books,music';

-- Existing profiles keep their selected media types as a comma-separated list.
-- Enable the new type for existing users while preserving all previous choices.
update profiles
set enabled_media_types = concat_ws(',', nullif(enabled_media_types, ''), 'music')
where not exists (
  select 1
  from unnest(string_to_array(coalesce(enabled_media_types, ''), ',')) as media_type
  where btrim(media_type) = 'music'
);

-- Create user challenges (year + medium specific goals)
create table if not exists
  user_challenges (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users on delete cascade,
    medium text not null,
    year int not null,
    challenge_type text not null check (challenge_type in ('count', 'pages', 'completion')),
    label text not null,
    target_count int not null check (target_count > 0),
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now(),
    unique (user_id, medium, year, challenge_type)
  );

alter table user_challenges enable row level security;

drop policy if exists "Users can view all challenges." on user_challenges;
create policy "Users can view all challenges." on user_challenges
  for select using (true);

drop policy if exists "Users can insert own challenges." on user_challenges;
create policy "Users can insert own challenges." on user_challenges
  for insert with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update own challenges." on user_challenges;
create policy "Users can update own challenges." on user_challenges
  for update using ((select auth.uid()) = user_id);

drop policy if exists "Users can delete own challenges." on user_challenges;
create policy "Users can delete own challenges." on user_challenges
  for delete using ((select auth.uid()) = user_id);

-- Stored procedure for upserting preferences
CREATE OR REPLACE FUNCTION upsert_and_change_factor(r_user_preference_id bigint, r_tmdb_id bigint, r_name varchar(50), r_factor real) RETURNS VOID AS $$
BEGIN
    INSERT INTO preferences (user_preference_id, tmdb_id, name, factor)
    VALUES (r_user_preference_id, r_tmdb_id, r_name, r_factor)
    ON CONFLICT (user_preference_id, tmdb_id)
    DO UPDATE SET factor = preferences.factor + r_factor;
END;
$$ LANGUAGE plpgsql;

-- Keep login metadata private instead of storing it on public profiles.
-- Supabase Auth also maintains auth.users.last_sign_in_at, but that schema is
-- not exposed to the client through the normal publishable-key API.
create table if not exists user_login_metadata (
  user_id uuid not null references auth.users on delete cascade primary key,
  last_login_at timestamp with time zone not null default now()
);

alter table user_login_metadata enable row level security;

drop policy if exists "Users can view their own login metadata." on user_login_metadata;
create policy "Users can view their own login metadata."
  on user_login_metadata
  for select using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert their own login metadata." on user_login_metadata;
create policy "Users can insert their own login metadata."
  on user_login_metadata
  for insert with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own login metadata." on user_login_metadata;
create policy "Users can update their own login metadata."
  on user_login_metadata
  for update using ((select auth.uid()) = user_id);

-- Track which release changelog each user has acknowledged.
-- The release version is part of the primary key so a new release can be shown
-- once to every user without showing older releases again.
create table if not exists user_release_acknowledgements (
  user_id uuid not null references auth.users on delete cascade,
  release_version text not null,
  acknowledged_at timestamp with time zone not null default now(),
  primary key (user_id, release_version)
);

alter table user_release_acknowledgements enable row level security;

drop policy if exists "Users can view their own release acknowledgements." on user_release_acknowledgements;
create policy "Users can view their own release acknowledgements."
  on user_release_acknowledgements
  for select using ((select auth.uid()) = user_id);

drop policy if exists "Users can acknowledge releases for themselves." on user_release_acknowledgements;
create policy "Users can acknowledge releases for themselves."
  on user_release_acknowledgements
  for insert with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own release acknowledgements." on user_release_acknowledgements;
create policy "Users can update their own release acknowledgements."
  on user_release_acknowledgements
  for update using ((select auth.uid()) = user_id);

-- Notification preferences and activity tracking
-- These objects are kept in this canonical schema so the same file can be
-- applied to a fresh or an already-running Supabase project.

create table if not exists notification_preferences (
  user_id uuid primary key references auth.users on delete cascade,
  notifications_enabled boolean not null default true,
  preferences jsonb not null default '{
    "games": {"backlog_adds": true, "regular_adds": true},
    "movies": {"backlog_adds": true, "regular_adds": true},
    "shows": {"backlog_adds": true, "regular_adds": true},
    "books": {"backlog_adds": true, "regular_adds": true},
    "music": {"backlog_adds": true, "regular_adds": true}
  }'::jsonb,
  updated_at timestamptz not null default now()
);

alter table notification_preferences enable row level security;

drop policy if exists "Users can view their own notification preferences" on notification_preferences;
create policy "Users can view their own notification preferences" on notification_preferences
  for select using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert their own notification preferences" on notification_preferences;
create policy "Users can insert their own notification preferences" on notification_preferences
  for insert with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own notification preferences" on notification_preferences;
create policy "Users can update their own notification preferences" on notification_preferences
  for update using ((select auth.uid()) = user_id);

create table if not exists user_activities (
  id bigint primary key generated always as identity,
  user_id uuid not null references auth.users on delete cascade,
  activity_type text not null check (activity_type in ('add', 'update', 'delete', 'follow', 'recommendation', 'recommendation_response')),
  media_type text check (media_type in ('games', 'movies', 'shows', 'books', 'music')),
  media_title text,
  details jsonb,
  created_at timestamptz not null default now()
);

-- Repair the media type constraint on notification tables created before Music.
do $$
declare
  constraint_name text;
begin
  for constraint_name in
    select pg_constraint.conname
    from pg_constraint
    join pg_class on pg_class.oid = pg_constraint.conrelid
    join pg_namespace on pg_namespace.oid = pg_class.relnamespace
    where pg_namespace.nspname = 'public'
      and pg_class.relname = 'user_activities'
      and pg_constraint.contype = 'c'
      and pg_get_constraintdef(pg_constraint.oid) like '%media_type%'
  loop
    execute format('alter table public.user_activities drop constraint %I', constraint_name);
  end loop;

  alter table public.user_activities
    add constraint user_activities_media_type_check
    check (media_type in ('games', 'movies', 'shows', 'books', 'music'));
end;
$$;

create index if not exists idx_user_activities_user_id on user_activities(user_id);
create index if not exists idx_user_activities_created_at on user_activities(created_at desc);

alter table user_activities enable row level security;

drop policy if exists "Users can insert their own activities" on user_activities;
create policy "Users can insert their own activities" on user_activities
  for insert with check ((select auth.uid()) = user_id);

drop policy if exists "Activities are viewable by everyone" on user_activities;
create policy "Activities are viewable by everyone" on user_activities
  for select using (true);

drop policy if exists "Users can delete their own activities" on user_activities;
create policy "Users can delete their own activities" on user_activities
  for delete using ((select auth.uid()) = user_id);

create table if not exists notification_read_status (
  id bigint primary key generated always as identity,
  user_id uuid not null references auth.users on delete cascade,
  last_read_at timestamptz not null default now(),
  unique(user_id)
);

alter table notification_read_status enable row level security;

drop policy if exists "Users can view their own read status" on notification_read_status;
create policy "Users can view their own read status" on notification_read_status
  for select using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert their own read status" on notification_read_status;
create policy "Users can insert their own read status" on notification_read_status
  for insert with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own read status" on notification_read_status;
create policy "Users can update their own read status" on notification_read_status
  for update using ((select auth.uid()) = user_id);

create table if not exists dismissed_activities (
  id bigint primary key generated always as identity,
  user_id uuid not null references auth.users on delete cascade,
  activity_id bigint not null references user_activities on delete cascade,
  dismissed_at timestamptz not null default now(),
  unique(user_id, activity_id)
);

create index if not exists idx_dismissed_activities_user_id on dismissed_activities(user_id);
create index if not exists idx_dismissed_activities_activity_id on dismissed_activities(activity_id);
create index if not exists idx_dismissed_activities_dismissed_at on dismissed_activities(dismissed_at desc);

alter table dismissed_activities enable row level security;

drop policy if exists "Users can view their own dismissed activities" on dismissed_activities;
create policy "Users can view their own dismissed activities" on dismissed_activities
  for select using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert their own dismissed activities" on dismissed_activities;
create policy "Users can insert their own dismissed activities" on dismissed_activities
  for insert with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their own dismissed activities" on dismissed_activities;
create policy "Users can delete their own dismissed activities" on dismissed_activities
  for delete using ((select auth.uid()) = user_id);
